FROM selenium/standalone-chrome:latest
#FROM selenium/standalone-chrome:4.9.0-20230422

# Establece el tamaño de la memoria compartida para el contenedor

# Establece la resolución de la pantalla para el contenedor
ENV SE_VNC_NO_PASSWORD=1
#Establece el tiempo antes de timeout:
ENV SE_NODE_SESSION_TIMEOUT=15

# Expone el puerto 4444
EXPOSE 4444