#25/11/2023

FROM selenium/standalone-chrome:119.0

# Establece la resolución de la pantalla para el contenedor
ENV SE_VNC_NO_PASSWORD=1
#Establece el tiempo antes de timeout:
ENV SE_NODE_SESSION_TIMEOUT=12
#Establece la maxima cantidad de sesiones:
ENV SE_NODE_MAX_SESSIONS=4

# Expone el puerto 4444
EXPOSE 4444